### ISSUE TITLE
System.IO.FileNotFoundException：Interop.SolidEdgePart

### ISSUE THREAD

**Issue by xuetongoll** [SolidEdgeCommunity/SDK#2]
When I try to add a path in DemoAddin, it throws an exception that Interop.SolidEdgePart.dll cannot be found,
Also when I reference [Interop.SolidEdge](https://github.com/SolidEdgeCommunity/Interop.SolidEdge), this code is correct

![image](https://user-images.githubusercontent.com/31362374/147727936-c2fef34a-6f15-4b94-ac0f-8cbed9030b6e.png)

**Comment by jlnewell** [comment]
The DemoAddIn compiles and executes without issue as-is. If you are unable to determine what the issue is, I would suggest starting over with a fresh copy of the DemoAddIn.

By default, "Interop.SolidEdgePart.dll" is generated at compile time, [due to this line in the DemoAddIn.csproj](https://github.com/SolidEdgeCommunity/SDK/blob/master/samples/addin/DemoAddIn/cs/DemoAddIn/DemoAddIn.csproj#L192) and should be in the bin\Debug folder after compile if EmbedInteropTypes = False.

[Interop.SolidEdge](https://github.com/SolidEdgeCommunity/Interop.SolidEdge) is no longer supported and should not be referenced.

Please use the [Solid Edge Developer Forums](https://community.sw.siemens.com/s/topic/0TO4O000000Mij0WAC/solid-edge-developer) for general questions.
